[package]
name = "tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
config = "0.14.1"
reqwest = "0.12.9"
serde = { version="1.0.215", features=[ "derive" ] }
tokio = { version="1.42.0", features=[ "macros", "rt-multi-thread" ] }
uuid = { version="1.11.0", features=[ "v4" ] }

[dependencies.sqlx]
version = "0.8.2"
features = [
    "runtime-tokio",
    "postgres",
    "uuid",
    "chrono", #日期时间映射支持
]
