web:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  db_name: "postgres"
email_client:
  base_url: "http://localhost"
  sender: "test@mailsire.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
